const APP_VERSION='1.0.0-prototype';
const items=[
{id:1,name:'Chunky Crochet Throw',price:38,cat:'Handmade & Homegrown',type:'crochet',fulfill:'Pickup or shipping',status:'Available',desc:'A soft, handmade throw in a warm neutral color. One currently available.'},
{id:2,name:'Women’s Linen Shirt',price:12,cat:'Clothing',type:'clothing',fulfill:'Pickup or shipping',status:'Available',desc:'Gently used linen blend shirt in excellent condition.'},
{id:3,name:'Wooden Side Table',price:24,cat:'Everyday Items',type:'everyday',fulfill:'Local pickup',status:'Available',desc:'Compact wooden side table with a warm natural finish.'},
{id:4,name:'Paracord Keychain Set',price:10,cat:'Handmade & Homegrown',type:'crochet',fulfill:'Pickup or shipping',status:'Pending',desc:'Handmade paracord keychain set. This one is currently pending.'},
{id:5,name:'Kids Rain Jacket',price:8,cat:'Clothing',type:'clothing',fulfill:'Pickup or shipping',status:'Available',desc:'Lightweight kids rain jacket, gently used.'},
{id:6,name:'Farm Stand Herb Bundle',price:6,cat:'Handmade & Homegrown',type:'crochet',fulfill:'Local pickup',status:'Available',desc:'Fresh seasonal herb bundle, while available.'},
{id:7,name:'Woven Storage Basket',price:14,cat:'Everyday Items',type:'everyday',fulfill:'Local pickup',status:'Available',desc:'Neutral woven basket for toys, blankets, or household storage.'},
{id:8,name:'Crochet Market Bag',price:22,cat:'Handmade & Homegrown',type:'crochet',fulfill:'Pickup or shipping',status:'Request',desc:'Handmade crochet market bag available by request.'}
];
let cart=[],current=items[0],shopSearch='';
function money(n){return '$'+n.toFixed(2)}
function productCard(x){const action=x.status==='Pending'?'Claim Next':x.status==='Request'?'Request item':'Add to cart';return `<article class="card"><button style="display:block;width:100%;border:0;padding:0;color:inherit" onclick="openProduct(${x.id})"><div class="photo ${x.type}"><span class="badge ${x.status==='Pending'?'pending':''}">${x.status}</span><div class="shape"></div></div></button><div class="cardbody"><div class="meta"><h3>${x.name}</h3><span class="price">$${x.price}</span></div><div class="fulfill">${x.fulfill}</div><button class="smallbtn" onclick="${x.status==='Pending'?`toast('You are next in line for ${x.name}')`:x.status==='Request'?`openProduct(${x.id})`:`quickAdd(${x.id})`}">${action}</button></div></article>`}
function renderProducts(){document.getElementById('homeProducts').innerHTML=items.slice(0,4).map(productCard).join('');let list=items;const cat=document.getElementById('categoryFilter')?.value;if(cat&&cat!=='All categories')list=list.filter(x=>x.cat===cat);const f=document.getElementById('fulfillFilter')?.value;if(f==='Shipping available')list=list.filter(x=>x.fulfill.includes('shipping'));if(f==='Local pickup')list=list.filter(x=>x.fulfill.includes('pickup'));if(shopSearch)list=list.filter(x=>(x.name+' '+x.cat).toLowerCase().includes(shopSearch.toLowerCase()));document.getElementById('shopProducts').innerHTML=list.length?list.map(productCard).join(''):'<div class="empty">No items match those filters.</div>'}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='cart')renderCart()}
function filterShop(cat){showView('shop');document.getElementById('categoryFilter').value=cat;renderProducts()}
function openProduct(id){current=items.find(x=>x.id===id);document.getElementById('detailCat').textContent=current.cat;document.getElementById('detailName').textContent=current.name;document.getElementById('detailPrice').textContent='$'+current.price;document.getElementById('detailDesc').textContent=current.desc;document.getElementById('detailAdd').textContent=current.status==='Pending'?'Claim Next':current.status==='Request'?'Send item request':'Add to cart';showView('product')}
function selectChoice(el){el.parentElement.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function quickAdd(id){const x=items.find(i=>i.id===id);cart.push(x);updateCount();toast(`${x.name} added to cart`)}
function addCurrentToCart(){if(current.status==='Pending'){toast(`You are next in line for ${current.name}`);return}if(current.status==='Request'){toast('Item request opened — we’ll confirm it can be made');return}quickAdd(current.id);showView('cart')}
function updateCount(){document.getElementById('cartCount').textContent=cart.length}
function removeCart(i){cart.splice(i,1);updateCount();renderCart()}
function renderCart(){const box=document.getElementById('cartItems');if(!cart.length){box.innerHTML='<div class="empty"><h3>Your cart is ready for good finds.</h3><p>Add items, change your mind, and remove them anytime.</p><button class="btn" onclick="showView(\'shop\')">Start shopping</button></div>'}else box.innerHTML=cart.map((x,i)=>`<div class="cartitem"><div class="thumb"></div><div><h3>${x.name}</h3><div class="muted" style="font-size:13px">${x.fulfill}</div><button class="textbtn" onclick="removeCart(${i})">Remove</button></div><strong>$${x.price}</strong></div>`).join('');const sum=cart.reduce((a,x)=>a+x.price,0);document.getElementById('subtotal').textContent=money(sum);document.getElementById('total').textContent=money(sum)}
function selectRadio(el){el.parentElement.querySelectorAll('.radioCard').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function setMethod(el,method){selectRadio(el);document.getElementById('methodNote').textContent=method==='pickup'?'We’ll contact you to arrange pickup. No pickups before 10 AM or from Friday 6 PM through Sunday 10 AM.':'We’ll calculate the actual label and packing-material cost, then email a PayPal invoice due within 24 hours.'}
function submitClaim(){toast('Claim DHS-1043 submitted — items are now pending');setTimeout(()=>showView('claims'),900)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));renderProducts();updateCount();
